version: '2'

services:

  ui:
    build:
      context: ./
      dockerfile: ./helpers/Dockerfile
    image: open-home-ui:latest
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
    links:
      - "db"
    volumes: # for development purposes
      - ./src:/usr/app/src

  db:
    image: mongo:latest

