version: '2'

services:

    broker:
        build:
            context: ./
            dockerfile: ./helpers/Dockerfile-broker
        image: open-iot-broker:latest
        hostname: broker
        ports:
            - 0.0.0.0:1883:1883   # mqtt port
            - 0.0.0.0:15675:15675 # web mqtt port
        environment:
            RABBITMQ_ERLANG_COOKIE: <erlang-cookie>

    ui:
        build:
            context: ./
            dockerfile: ./helpers/Dockerfile-ui
        image: open-iot-ui:latest
        hostname: ui
        ports:
            - 0.0.0.0:8080:8080
        # depends_on:
        #     - db
        # This is development configuration
        environment:
            DB_CONNECTION: mongodb://db.iot.vorotnikov.net/dev
            ENCRYPTION_SECRET: my-super-secret-pass             # JWT signing
            BROKER_HOST: broker                                 # ui-broker connection
            HANDLER_KEY: handler-key                            # ui credentials
            HANDLER_SECRET: handler-secret                      # ui credentials
        volumes: # for development purposes
            - ./src:/usr/app/src

    # This is local DB service for whenever the remote db is not available
    # db:
    #     image: mongo:latest
    #     hostname: db
