version: '2.1'

services:

    # reverse proxy to backend doing SSL offloading
    proxy:
        image: pvorotnikov/open-iot-proxy:latest
        ports:
            - 80:80
            - 443:443
            - 1883:1883
            - 8883:8883
            - 15675:15675
            - 15676:15676
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /path/to/certs:/etc/nginx/certs

    # broker service
    broker:
        image: pvorotnikov/open-iot-broker:latest
        hostname: broker
        environment:
            RABBITMQ_ERLANG_COOKIE: erlang-cookie                  # change this

    # ui and api service
    ui:
        image: pvorotnikov/open-iot-ui:latest
        hostname: ui
        restart: always
        environment:
            VIRTUAL_HOST: example.com                              # how is the host reached
            DB_CONNECTION: mongodb://db.example.com/prod           # db connection string
            ENCRYPTION_SECRET: my-super-secret-key                 # change this (JWT)
            HANDLER_KEY: broker-super-secret key                   # change this (broker client)
            HANDLER_SECRET: broker-super-secret-pass               # change this (broker client)
            BROKER_HOST: broker
