version: '2'

services:

    broker:
        build:
            context: ./
            dockerfile: ./helpers/Dockerfile-broker
        hostname: broker
        ports:
            - 0.0.0.0:1883:1883   # mqtt port
            - 0.0.0.0:15675:15675 # web mqtt port
        environment:
            RABBITMQ_ERLANG_COOKIE: <erlang-cookie>

    ui:
        build:
            context: ./
            dockerfile: ./helpers/Dockerfile-ui
        image: open-iot-ui:latest
        hostname: ui
        ports:
            - 0.0.0.0:8080:8080
        depends_on:
            - broker
            - db
        #volumes: # for development purposes
        #    - ./src:/usr/app/src

    db:
        image: mongo:latest
        hostname: db
        ports:
            - 127.0.0.1:27017:27017 # expose for debugging

