version: '2'

services:

    proxy:
        build:
            context: ./
            dockerfile: ./proxy/Dockerfile
        image: open-iot-proxy:latest
        ports:
            - 80:80
            - 443:443
            - 1883:1883
            - 8883:8883
            - 15675:15675
            - 15676:15676
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/server_key.pem:/etc/nginx/certs/127.0.0.1.key
            - ./certs/server_certificate.pem:/etc/nginx/certs/127.0.0.1.crt

    broker:
        build:
            context: ./
            dockerfile: ./broker/Dockerfile
        image: open-iot-broker:latest
        hostname: broker
        environment:
            RABBITMQ_ERLANG_COOKIE: <erlang-cookie>

    ui:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: open-iot-ui:latest
        hostname: ui
        environment:
            VIRTUAL_HOST: 127.0.0.1                             # how is the host reached
            DB_CONNECTION: mongodb://db/openiot
            ENCRYPTION_SECRET: my-super-secret-pass             # JWT signing
            BROKER_HOST: broker                                 # ui-broker connection
            HANDLER_KEY: handler-key                            # ui credentials
            HANDLER_SECRET: handler-secret                      # ui credentials
        depends_on:
            - db
        volumes:
            - ./src:/usr/app/src

    db:
        image: mongo:latest
        ports:
            - 27017:27017
        hostname: db
